//! Tauri IPC 命令列表集中于此，按域分段注释；在 `lib.rs` 用 `didclaw_invoke_handlers!()` 展开，
//! 避免 `generate_handler!` 放在泛型辅助函数里导致 `AppHandle` / `R` 推断失败（Tauri 2）。

/// 在 `lib.rs` 的 `Builder` 链上写：`.invoke_handler(didclaw_invoke_handlers!())`
#[macro_export]
macro_rules! didclaw_invoke_handlers {
    () => {
        tauri::generate_handler![
            // ─── 预览 / Shell / 对话框 ─────────────────────────────
            crate::commands::preview_open_local,
            crate::commands::preview_libre_office_status,
            crate::commands::preview_open_libre_office_download_page,
            crate::commands::preview_show_libre_office_install_dialog,
            crate::commands::shell_open_file_url,
            crate::commands::shell_open_external_url,
            crate::commands::dialog_save_base64_file,
            crate::commands::file_save_copy_as,
            crate::commands::shell_prepare_email_with_local_file,
            crate::commands::shell_copy_local_file_for_share,
            crate::commands::dialog_open_file,
            // ─── OpenClaw 环境 / 网关本地配置 / KV / 进程 ───────────
            crate::commands::get_open_claw_setup_status,
            crate::commands::check_openclaw_update,
            crate::commands::run_ensure_openclaw_windows_install,
            crate::commands::read_gateway_local_config,
            crate::commands::write_gateway_local_config,
            crate::commands::didclaw_kv_get,
            crate::commands::didclaw_kv_set,
            crate::commands::didclaw_kv_remove,
            crate::commands::ensure_open_claw_gateway,
            crate::commands::restart_open_claw_gateway,
            crate::commands::stop_open_claw_gateway,
            // ─── 插件 ─────────────────────────────────────────────
            crate::commands::openclaw_plugins_install,
            crate::commands::plugins_pick_package_file,
            crate::commands::openclaw_plugins_list,
            crate::commands::openclaw_plugins_inspect,
            crate::commands::openclaw_plugins_set_enabled,
            crate::commands::openclaw_plugins_update,
            crate::commands::openclaw_plugins_uninstall,
            // ─── OpenClaw 技能市场 / Clawhub ───────────────────────
            crate::commands::openclaw_skills_list,
            crate::commands::openclaw_skills_search,
            crate::commands::openclaw_skills_info,
            crate::commands::openclaw_skills_install,
            crate::commands::openclaw_skills_update,
            crate::commands::openclaw_skills_uninstall,
            crate::commands::openclaw_skills_check,
            crate::commands::clawhub_packages_search,
            crate::commands::clawhub_package_detail,
            crate::commands::clawhub_skill_detail,
            crate::commands::clawhub_download_skill_zip,
            // ─── 网关隧道 / 模型与 Provider / 工具配置 ───────────────
            crate::commands::gateway_tunnel_open,
            crate::commands::gateway_tunnel_send,
            crate::commands::gateway_tunnel_close,
            crate::commands::read_open_claw_model_config,
            crate::commands::write_open_claw_model_config,
            crate::commands::write_open_claw_env,
            crate::commands::read_open_claw_tools_profile,
            crate::commands::write_open_claw_tools_profile,
            crate::commands::write_open_claw_skill_enabled,
            crate::commands::restore_open_claw_config_to_latest_backup,
            crate::commands::read_open_claw_providers,
            crate::commands::read_open_claw_ai_snapshot,
            crate::commands::write_open_claw_providers_patch,
            crate::commands::read_open_claw_agents_list,
            crate::commands::write_open_claw_agents_list_merge,
            crate::commands::sync_openclaw_subagent_auth_profiles_from_main,
            crate::commands::read_open_claw_tools_agent_to_agent,
            crate::commands::write_open_claw_tools_agent_to_agent_merge,
            // ─── 内置 skills 安装目录 / Doctor / OAuth / 备份 ───────
            crate::commands::skills_default_install_root,
            crate::commands::skills_list_installed,
            crate::commands::skills_install_zip_base64,
            crate::commands::skills_install_zip_path,
            crate::commands::skills_install_from_folder,
            crate::commands::skills_delete,
            crate::commands::skills_pick_zip_file,
            crate::commands::skills_pick_folder,
            crate::commands::read_workspace_identity,
            crate::openclaw_workspace_memory::list_openclaw_workspace_memory,
            crate::commands::run_openclaw_doctor,
            crate::commands::run_openclaw_onboard,
            crate::commands::run_minimax_oauth,
            crate::commands::run_openai_codex_oauth,
            crate::commands::estimate_openclaw_backup_size,
            crate::commands::backup_openclaw_config,
            crate::commands::restore_openclaw_config,
            // ─── 渠道配置 / 更新 / 系统 ─────────────────────────────
            crate::commands::write_channel_config,
            crate::commands::check_channel_plugin_installed,
            crate::commands::cleanup_channel_residue,
            crate::commands::configure_feishu_plugin,
            crate::commands::start_channel_qr_flow,
            crate::commands::check_didclaw_update,
            crate::commands::install_didclaw_update,
            crate::commands::quit_app,
            crate::commands::get_autostart_enabled,
            crate::commands::set_autostart_enabled,
            crate::commands::get_prevent_sleep_enabled,
            crate::commands::set_prevent_sleep_enabled,
            crate::commands::get_global_shortcut_key,
            crate::commands::set_global_shortcut_key,
            crate::commands::didclaw_set_app_locale,
            crate::commands::save_chat_attachment,
            // ─── 实验：pheromone 图 / 实时补丁面板 ───────────────────
            crate::pheromone::read_pheromone_graph,
            crate::pheromone::write_pheromone_graph,
            crate::pheromone::inject_pheromone_agents_md,
            crate::commands::live_edit_pick_workspace,
            crate::commands::live_edit_apply_unified_diff,
        ]
    };
}
